## fixme: adapt this
export SERVER=127.0.0.1
# generate certs for Google Chrome
if [ ! -f /etc/pki/trust/anchors/$SERVER.cert ]; then
  wget http://$SERVER/pub/RHN-ORG-TRUSTED-SSL-CERT -O /etc/pki/trust/anchors/$SERVER.cert
  update-ca-certificates
  certutil -d sql:/root/.pki/nssdb -A -t TC -n "serverundertest" -i  /etc/pki/trust/anchors/$SERVER.cert
fi
